# Generated by Django 4.0.4 on 2022-06-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de la categoria')),
                ('nombrecategoria', models.CharField(max_length=45, verbose_name='Nombre de las categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de estado ')),
                ('nombreestado', models.CharField(max_length=25, verbose_name='Nombre de estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idpelicula', models.AutoField(primary_key=True, serialize=False, verbose_name='codigo de la pelicula')),
                ('nombrepelicula', models.CharField(max_length=45, verbose_name='Nombre de la pelicula')),
                ('director', models.CharField(max_length=30, verbose_name='Nombre del director')),
                ('reparto', models.CharField(max_length=50, verbose_name='Nombres del reparto principal de la pelicula')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion de la pelicula')),
                ('imagen', models.ImageField(null=True, upload_to='peliculasimagen')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de rol ')),
                ('nombrerol', models.CharField(max_length=25, verbose_name='Nombre de rol')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idcuenta', models.AutoField(primary_key=True, serialize=False, verbose_name='codigo de la cuenta')),
                ('usuario', models.CharField(max_length=25, verbose_name='Nombre de la cuenta')),
                ('correo', models.CharField(max_length=45, verbose_name='correo electronico')),
                ('contraseña', models.CharField(max_length=30, verbose_name='contraseña')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Categoriapelicula',
            fields=[
                ('idtiposcategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de todas las categorias de cada peliculas')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('idcalificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='id calificacion')),
                ('puntuacion', models.IntegerField(blank=True, verbose_name='puntuacion de la persona a la pelicula')),
                ('comentario', models.CharField(blank=True, max_length=70, verbose_name='comentarios a la pelicula')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuenta')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelicula')),
            ],
        ),
    ]
